---
title: "JEM Figure 4"
author: "Maksym Zarodniuk"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: html_document
---

```{r setup, warning=F, message=F}
library(MetBrewer)
library(ggrepel)
library(scales)
library(cowplot)
library(tidyverse)
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
library(msigdbr)
library(clusterProfiler)
library(enrichplot)
library(org.Mm.eg.db)
library(patchwork)
library(lemon)
library(rstatix)
library(ggpubr)

gntp_col <- met.brewer("Nizami", 2)[c(2, 1)]
names(gntp_col) <- c("HE", "KO")
```

## 4A

```{r}
dfA <- read_tsv("data/Figure_4/merged_de_data_wide.tsv")

dfA <- dfA %>%
  select(SYMBOL, FC = FC.Rat, FDR = FDR.Rat) %>%
  mutate(Log2FC = log2(abs(FC)),
         Log2FC = ifelse(FC < 0, Log2FC*-1, Log2FC)) %>%
  mutate(logP = -log10(FDR)) %>%
  mutate(DE = if_else(FDR < .05 & Log2FC > 1, "Upregulated", "Not changed"),
           DE = if_else(FDR < .05 & Log2FC < -1, "Downregulated", DE),
         Label = ifelse(DE!="Not changed", SYMBOL, "")) %>%
  replace_na(list(ISG = 0))

col_vec <- c(met.brewer("Nizami", 2)[2],
             "#d3d3d3",
             met.brewer("Nizami", 2)[1])
names(col_vec) <- c("Downregulated", "Not changed", "Upregulated")

genes_to_show <- c("Ifit2", "Irf7", "Mx1", "Mx2", "Oas2", "Oas1a", "Oas1b", "Ifi47", "Ins2", "Defa23", "Nts", "Klk1", "Gal", "Gip")

genes_to_show <- dfA %>% filter(SYMBOL %in% genes_to_show)
genes_to_show$Label <- paste0("italic('", genes_to_show$Label, "')")

P_A <- ggplot(dfA %>%
              arrange((DE)),
            aes(x=Log2FC, y=logP, color=factor(DE))) +
  geom_point(size=0.1) +
  coord_cartesian(xlim=c(-7, 3), ylim = c(0, 6)) +
  geom_text_repel(data = genes_to_show,
                  aes(x = Log2FC, y = logP, label = Label),
                  min.segment.length = .5,
                  seed = 3,
                  box.padding = .5,
                  force = 5,
                  show.legend = FALSE,
                  max.overlaps =30,
                  size=5,
                  parse = T
  ) +
  scale_color_manual(values = col_vec[names(col_vec) %in% as.character(unique(dfA$DE))]) +
  theme_cowplot(16) +
  labs(x=expression(log[2]*"FC"),
       y = expression(-log[10]*"FDR")) +
  theme(legend.position = "none")

P_A
```

## 4B

```{r}
dfB <- read_tsv("data/Figure_4/downregulated_GO.tsv")

dfB$GeneRatioDecimal <- sapply(dfB$GeneRatio, function(x) {eval(parse(text=x))})
dfB <- dfB %>% mutate(log10p = -log10(p.adjust))


P_B <- ggplot(dfB %>%
         head(10), aes(x = GeneRatioDecimal, y = reorder(Description, GeneRatioDecimal), 
                          color = log10p, size = Count)) + 
  geom_point() +
  scale_size(range = c(0, 4)) +
  scale_colour_gradient2(
    low = ("white"),
    mid = ("white"),
    high = met.brewer("Nizami", 2)[2],
    midpoint = -log10(0.05)
  ) +
  theme_cowplot() + 
  ylab("") + 
  xlab("GeneRatio") +
  coord_cartesian(xlim=c(0, 0.15)) +
  scale_y_discrete(position = "right") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

P_B
```

## 4C

```{r}
qpcr_data <- read.csv("data/Figure_4/qPCR data.csv")
qpcr_data$Gene[qpcr_data$Gene==""] <- NA
qpcr_data <- qpcr_data %>%
  fill(Gene) %>%
  pivot_longer(!c(Gene, Tissue), names_to = "Group", values_to = "FC") %>%
  separate(Group, c("Age", "Genotype"), sep="_")

qpcr_data$Age <- factor(qpcr_data$Age, levels = c("Young", "Old"))
```

### Thymus

```{r}
qpcr_data_THY <- qpcr_data %>% filter(Tissue == "Thymus")

stat.test <- qpcr_data_THY %>%
  group_by(Gene, Age) %>%
  t_test(FC ~ Genotype) %>%
  adjust_pvalue() %>%
  add_significance("p") %>%
  add_xy_position(x = "Age", dodge = 0.8, scales="free_y") %>%
  filter(p.signif != "ns")

qpcr_data_THY_summarized <- qpcr_data_THY %>%
  group_by(Gene, Age, Genotype) %>%
  mutate(n = n()) %>%
  summarise(Mean = mean(FC), SEM = sd(FC)/sqrt(n)) %>%
  distinct()

p_THY <- ggplot(qpcr_data_THY_summarized, aes(Age, Mean, color = Genotype)) + 
  geom_errorbar(aes(x=Age, ymin=Mean-SEM, ymax=Mean+SEM), width=0.4, position = position_dodge(.8)) +
  geom_errorbar(aes(x=Age, ymin=Mean, ymax=Mean), width=0.6, position = position_dodge(.8)) +
  geom_dotplot(data = qpcr_data_THY, aes(x=Age, y=FC, color = Genotype), binaxis = "y", stackdir = "center", position = position_dodge(.8)) +
  facet_wrap(~Gene, scales="free_y", ncol=2) +
  stat_pvalue_manual(
    stat.test,  label = "p.signif", tip.length = 0, hide.ns = F
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.4))) +
  scale_color_manual(values = gntp_col) +
  theme_cowplot(15) +
  theme(strip.background=element_rect(colour="white",
                                    fill="white"), legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        strip.text.x = element_text(face = "bold.italic"),
        plot.title = element_text(size=13)) +
  labs(x = NULL, y = NULL) +
  ggtitle("Thymus")
```

Log scale for Ifit3
```{r}
stat.test <- qpcr_data_THY %>%
  group_by(Gene, Age) %>%
  t_test(FC ~ Genotype) %>%
  adjust_pvalue() %>%
  add_significance("p") %>%
  add_xy_position(x = "Age", dodge = 0.8, scales="free_y") %>%
  filter(p.signif != "ns")

p_THY_log <- ggplot(qpcr_data_THY_summarized, aes(Age, Mean, color = Genotype)) + 
  geom_errorbar(aes(x=Age, ymin=Mean-SEM, ymax=Mean+SEM), width=0.4, position = position_dodge(.8)) +
  geom_errorbar(aes(x=Age, ymin=Mean, ymax=Mean), width=0.6, position = position_dodge(.8)) +
  geom_dotplot(data = qpcr_data_THY, aes(x=Age, y=FC, color = Genotype), binaxis = "y", stackdir = "center", position = position_dodge(.8)) +
  facet_wrap(~Gene, scales="free_y", ncol=2) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.4)), transform = "log10") +
  scale_color_manual(values = gntp_col) +
  theme_cowplot(15) +
  theme(strip.background=element_rect(colour="white",
                                    fill="white"), legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        strip.text.x = element_text(face = "bold.italic"),
        plot.title = element_text(size=13)) +
  labs(x = NULL, y = NULL) +
  ggtitle("Thymus")
```

### Spleen

```{r}
qpcr_data_SPL <- qpcr_data %>% filter(Tissue == "Spleen") %>% drop_na()

stat.test <- qpcr_data_SPL %>%
  group_by(Gene, Age) %>%
  t_test(FC ~ Genotype) %>%
  adjust_pvalue() %>%
  add_significance("p") %>%
  add_xy_position(x = "Age", dodge = 0.8, scales="free_y") %>%
  filter(p.signif != "ns")

qpcr_data_SPL_summarized <- qpcr_data_SPL %>%
  group_by(Gene, Age, Genotype) %>%
  mutate(n = n()) %>%
  summarise(Mean = mean(FC), SEM = sd(FC)/sqrt(n)) %>%
  distinct()

p_SPL <- ggplot(qpcr_data_SPL_summarized, aes(Age, Mean, color = Genotype)) + 
  geom_errorbar(aes(x=Age, ymin=Mean-SEM, ymax=Mean+SEM), width=0.4, position = position_dodge(.8)) +
  geom_errorbar(aes(x=Age, ymin=Mean, ymax=Mean), width=0.6, position = position_dodge(.8)) +
  geom_dotplot(data = qpcr_data_SPL, aes(x=Age, y=FC, color = Genotype), binaxis = "y", stackdir = "center", position = position_dodge(.8)) +
  facet_wrap(~Gene, scales="free_y", ncol=2) +
  stat_pvalue_manual(
    stat.test,  label = "p.signif", tip.length = 0, hide.ns = F
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.4))) +
  scale_color_manual(values = gntp_col) +
  theme_cowplot(15) +
  theme(strip.background=element_rect(colour="white",
                                    fill="white"), legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        strip.text.x = element_text(face = "bold.italic"),
        plot.title = element_text(size=13)) +
  labs(x = NULL, y = NULL) +
  ggtitle("Spleen")
```
### LN

```{r}
qpcr_data_LN <- qpcr_data %>% filter(Tissue == "LN") %>% drop_na()

stat.test <- qpcr_data_LN %>%
  group_by(Gene, Age) %>%
  t_test(FC ~ Genotype) %>%
  adjust_pvalue() %>%
  add_significance("p") %>%
  add_xy_position(x = "Age", dodge = 0.8, scales="free_y") %>%
  filter(p.signif != "ns")

qpcr_data_LN_summarized <- qpcr_data_LN %>%
  group_by(Gene, Age, Genotype) %>%
  mutate(n = n()) %>%
  summarise(Mean = mean(FC), SEM = sd(FC)/sqrt(n)) %>%
  distinct()

p_LN <- ggplot(qpcr_data_LN_summarized, aes(Age, Mean, color = Genotype)) + 
  geom_errorbar(aes(x=Age, ymin=Mean-SEM, ymax=Mean+SEM), width=0.4, position = position_dodge(.8)) +
  geom_errorbar(aes(x=Age, ymin=Mean, ymax=Mean), width=0.6, position = position_dodge(.8)) +
  geom_dotplot(data = qpcr_data_LN, aes(x=Age, y=FC, color = Genotype), binaxis = "y", stackdir = "center", position = position_dodge(.8)) +
  facet_wrap(~Gene, scales="free_y", ncol=2) +
  stat_pvalue_manual(
    stat.test,  label = "p.signif", tip.length = 0, hide.ns = F
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.4))) +
  scale_color_manual(values = gntp_col) +
  theme_cowplot(15) +
  theme(strip.background=element_rect(colour="white",
                                    fill="white"), legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        strip.text.x = element_text(face = "bold.italic"),
        plot.title = element_text(size=13)) +
  labs(x = NULL, y = NULL) +
  ggtitle("Lymph node")
```


```{r, fig.height=7, fig.width=15}
P_C <- p_THY + p_SPL + p_LN

P_C
```

## 4D

```{r}
de_data <- read_tsv("data/Figure_4/merged_de_data_wide.tsv")
sData <- read_tsv("data/Figure_4/sData.tsv")
merged_exprs_mtx_scaled <- read_tsv("data/Figure_4/merged_exprs_mtx_scaled.tsv")

de_data <- dplyr::select(de_data, SYMBOL, starts_with("DE")) %>%
    column_to_rownames("SYMBOL") %>%
    drop_na()

de_data[de_data==-1] <- 1
de_data <- de_data[rowSums(de_data) > 0,]
mat <- merged_exprs_mtx_scaled[merged_exprs_mtx_scaled$SYMBOL %in% rownames(de_data),]
mat <- as.data.frame(mat)
rownames(mat) <- mat$SYMBOL
mat$SYMBOL <- NULL
PCA_raw <- prcomp(t(mat), scale. = FALSE)
percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])
dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2],
                     Species = str_split(sData$Dataset, " ", Inf, T)[,1],
                    Genotype = sData$Genotype)

P_D <- ggplot(dataGG, aes(PC1, PC2)) +
    geom_point(aes(shape = Species, colour = Genotype), size=3) +
    xlab(paste0("PC1")) +
    ylab(paste0("PC2")) +
    theme(plot.title = element_text(hjust = 0.5)) +
  geom_hline(yintercept = 5, lty="dashed") +
  geom_vline(xintercept = 0, lty="dashed") +
    scale_color_manual(values = c(met.brewer("Nizami", 2)[2], met.brewer("Nizami", 2)[1])) +
    theme_cowplot(16)

P_D
```

## 4E

```{r}
isg_genes <- readLines("data/Figure_4/hits.txt")
merged_de_data <- read_tsv("data/Figure_4/merged_de_data_wide.tsv")
merged_exprs_mtx_scaled <- read_tsv("data/Figure_4/merged_exprs_mtx_scaled.tsv")
TRG_data <- read_tsv("data/Figure_4/TRG_data_Mm_gene_names.tsv")
sData <- read_tsv("data/Figure_4/sData.tsv")

# genes that are DE in at least one dataset
merged_de_data <- dplyr::select(merged_de_data, SYMBOL, starts_with("DE")) %>%
  column_to_rownames("SYMBOL") %>%
  drop_na()
merged_de_data[merged_de_data==-1] <- 1
merged_de_data <- merged_de_data[rowSums(merged_de_data) > 0,]

mat <- merged_exprs_mtx_scaled[merged_exprs_mtx_scaled$SYMBOL %in% rownames(merged_de_data),]
mat <- as.data.frame(mat)
rownames(mat) <- mat$SYMBOL
mat$SYMBOL <- NULL
rat_trg_genes <- TRG_data$SYMBOL.Mm[TRG_data$Species=="Rat"]
mouse_trg_genes <- TRG_data$SYMBOL.Mm[TRG_data$Species=="Mouse"]
rat_trg_genes <- !is.na(rat_trg_genes[match(rownames(mat), rat_trg_genes)])
mouse_trg_genes <- !is.na(mouse_trg_genes[match(rownames(mat), mouse_trg_genes)])

colAnn <- HeatmapAnnotation(Genotype = sData$Genotype,
                            which = 'col',
                            col = list("Genotype" = c('Ctrl' = met.brewer("Nizami", 2)[2], 'KO' = met.brewer("Nizami", 2)[1])),
                            simple_anno_size = unit(.15, "cm"),
                            gap = unit(1, 'mm'),
                            show_annotation_name = F)

dist_obj <- dist(mat)
set.seed(42)
hcl_obj <- hclust(dist_obj)
cl <- cutree(hcl_obj, k=4)

set.seed(444)
ht = Heatmap(mat,
        name = "scaled_expr", 
        cluster_columns = TRUE,
        show_column_dend = F,
        show_row_dend = F,
        row_split = cl,
        show_row_names = F,
        column_split = factor(str_split(sData$Dataset, " ", Inf, T)[,1]),
        cluster_column_slices = F,
        column_title_gp = gpar(fontsize = 10),
        column_gap = unit(0.5, "mm"),
        cluster_rows = TRUE,
        top_annotation = colAnn,
        show_column_names = FALSE,
        border = T,
        row_names_gp = gpar(fontsize = 10),
        width = unit(2*1.2, "cm"), 
        height = unit(4*1.5, "cm"),
        raster_quality = 4,
        heatmap_legend_param = list(title = "Scaled expr")) +
  Heatmap(rat_trg_genes + 0, name = "Rat TRA", col = c("0" = "white", "1" = "black"), 
        show_heatmap_legend = FALSE, width = unit(2.5, "mm"), column_names_gp = gpar(fontsize = 10)) +
  Heatmap(mouse_trg_genes + 0, name = "Mouse TRA", col = c("0" = "white", "1" = "black"), 
        show_heatmap_legend = FALSE, width = unit(2.5, "mm"), column_names_gp = gpar(fontsize = 10))

ht
```

```{r}
fisher.test(table(as.numeric(cl==2), as.numeric(mouse_trg_genes | rat_trg_genes)))
fisher.test(table(as.numeric(cl==2), as.numeric(rownames(mat) %in% isg_genes)))
```

## 4F

```{r}
source("util.R")

isg_genes <- readLines("data/Figure_4/hits.txt")
merged_de_data <- read_tsv("data/Figure_4/merged_de_data.tsv")
merged_de_data <- merged_de_data %>% group_by(Dataset) %>% distinct(SYMBOL, .keep_all = T)
merged_de_data <- merged_de_data %>% group_by(Dataset) %>% sample_n(9876)
merged_de_data$entrez_id <- mapIds(org.Mm.eg.db,
                      keys=merged_de_data$SYMBOL,
                      column="ENTREZID",
                      keytype="SYMBOL",
                      multiVals="first")

TERM2GENE <- data.frame(term = rep("ISG", length(isg_genes)), gene = isg_genes)

gsea_isg_rat <- run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Rat",], TERM2GENE)@result %>% mutate(Dataset = "Rat")
gsea_isg_mouseA <- run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Mouse A",], TERM2GENE)@result %>% mutate(Dataset = "Mouse A")
gsea_isg_mouseB <- run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Mouse B",], TERM2GENE)@result %>% mutate(Dataset = "Mouse B")
gsea_isg_mouseC <- run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Mouse C",], TERM2GENE)@result %>% mutate(Dataset = "Mouse C")
gsea_isg_mouseD <- run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Mouse D",], TERM2GENE)@result %>% mutate(Dataset = "Mouse D")

gsea_isg_ALL <- rbind(gsea_isg_rat, gsea_isg_mouseA, gsea_isg_mouseB, gsea_isg_mouseC, gsea_isg_mouseD)
rownames(gsea_isg_ALL) <- 1:nrow(gsea_isg_ALL)
gsea_isg_ALL$p.adjust <- p.adjust(gsea_isg_ALL$pvalue)
gsea_isg_ALL$logpadj <- -log10(gsea_isg_ALL$p.adjust)

P_F <- ggplot(gsea_isg_ALL, aes(x = reorder(Dataset, NES), y = NES, 
                          color = NES, size = logpadj)) + 
  geom_point() +
  scale_size(range = c(1, 7)) +
  scale_colour_gradient2(
    high = ("white"),
    mid = ("white"),
    low = met.brewer("Nizami", 2)[2],
    midpoint = -1
  ) +
  ylim(-2.6, -1.55) +
  theme_cowplot(14) + 
  ylab("NES") + 
  xlab(NULL) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

P_F
```

## 4G

```{r, fig.height=3, fig.width=8}
p1 <- gseaplot(run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Rat",], TERM2GENE), "ISG", color.vline = NA, by = "runningScore", color.line = met.brewer("Nizami", 2)[2]) + ggtitle("Rat") + xlab("Rank")  + theme_cowplot(14) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(size=14)) + ylab("ES") + ylim(-0.8, 0.05)
p2 <- gseaplot(run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Mouse A",], TERM2GENE), "ISG", color.vline = NA, by = "runningScore", color.line = met.brewer("Nizami", 2)[2]) + ggtitle("Mouse A") + xlab("Rank")  + theme_cowplot(14) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(size=14)) + ylab(NULL) + ylim(-0.8, 0.04)
p3 <- gseaplot(run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Mouse B",], TERM2GENE), "ISG", color.vline = NA, by = "runningScore", color.line = met.brewer("Nizami", 2)[2]) + ggtitle("Mouse B") + xlab("Rank")  + theme_cowplot(14) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(size=14)) + ylab(NULL) + ylim(-0.8, 0.04)
p4 <- gseaplot(run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Mouse C",], TERM2GENE), "ISG", color.vline = NA, by = "runningScore", color.line = met.brewer("Nizami", 2)[2]) + ggtitle("Mouse C") + xlab("Rank")  + theme_cowplot(14) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(size=14)) + ylab(NULL) + ylim(-0.8, 0.04)
p5 <- gseaplot(run_custom_GSEA(merged_de_data[merged_de_data$Dataset=="Mouse D",], TERM2GENE), "ISG", color.vline = NA, by = "runningScore", color.line = met.brewer("Nizami", 2)[2]) + ggtitle("Mouse D") + xlab("Rank")  + theme_cowplot(14) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(size=14)) + ylab(NULL) + ylim(-0.8, 0.04)

P_G <- p1 + p2 + p3 + p5 + p4 + plot_spacer() + plot_layout(nrow = 1, widths = c(1, 1, 1, 1, 1, 0.1))

P_G
```

## 4H

```{r}
merged_de_data <- read_tsv("data/Figure_4/merged_de_data_wide.tsv")
isg_genes <- readLines("data/Figure_4/hits.txt")
mat <- merged_de_data[merged_de_data$SYMBOL %in% isg_genes,] %>%
  column_to_rownames("SYMBOL") %>%
  dplyr::select(starts_with("FC"))

neg_bool <- mat < 0 & !is.na(mat)
mat <- log2(abs(mat))
mat[neg_bool] <- mat[neg_bool]*-1
mat <- mat[rowSums(is.na(mat[,1:4])) < 2 & !is.na(mat[,5]),]
colnames(mat) <- str_split(colnames(mat), "\\.", Inf, T)[,2]

ha <- rowAnnotation(LFC = anno_boxplot(t(mat)))
P_H <- Heatmap(t(mat),
        name = "log2FC", 
        right_annotation = ha,
        cluster_columns = TRUE,
        show_column_dend = F,
        show_row_dend = F,
        show_row_names = T,
        column_title_gp = gpar(fontsize = 10),
        column_gap = unit(0.5, "mm"),
        column_names_rot = 90,
        row_split = factor(str_split(colnames(mat), " ", Inf, T)[,1]),
        cluster_rows = TRUE,
        show_column_names = T,
        border = T,
        width = unit(16, "cm"), 
        height = unit(3, "cm"),
        column_names_gp = gpar(fontsize = 7),
        use_raster = TRUE,
        raster_quality = 4)

draw(P_H)
```

## 4I

```{r}
gntp_col <- met.brewer("Nizami", 2)[c(2, 1)]
names(gntp_col) <- c("WT", "KO")

qpcr_data <- read.csv("data/Figure_4/qPCR fr aire ENH KO mouse TY SP LN.csv")
qpcr_data <- qpcr_data %>%
  pivot_longer(!Gene, names_to = "Group", values_to = "FC") %>%
  separate(Group, c("Genotype", "Tissue"), sep="_")

qpcr_data$Gene <- first_upper(qpcr_data$Gene)
qpcr_data$Genotype <- factor(qpcr_data$Genotype, levels = c("WT", "KO"))
```

### Thymus

```{r}
qpcr_data_THY <- qpcr_data %>% filter(Tissue == "Thymus")

stat.test <- qpcr_data_THY %>%
  group_by(Gene) %>%
  t_test(FC ~ Genotype) %>%
  adjust_pvalue() %>%
  add_significance("p") %>%
  add_xy_position(x = "Genotype", dodge = 0.8, scales="free_y") %>%
  filter(p.signif != "ns")

qpcr_data_THY_summarized <- qpcr_data_THY %>%
  group_by(Gene, Genotype) %>%
  mutate(n = n()) %>%
  summarise(Mean = mean(FC), SEM = sd(FC)/sqrt(n)) %>%
  distinct()

p_THY <- ggplot(qpcr_data_THY_summarized, aes(Genotype, Mean, color = Genotype)) + 
  geom_errorbar(aes(x=Genotype, ymin=Mean-SEM, ymax=Mean+SEM), width=0.4, position = position_dodge(.8)) +
  geom_errorbar(aes(x=Genotype, ymin=Mean, ymax=Mean), width=0.6, position = position_dodge(.8)) +
  geom_dotplot(data = qpcr_data_THY, aes(x=Genotype, y=FC, color = Genotype), binaxis = "y", stackdir = "center", position = position_dodge(.8)) +
  facet_wrap(~Gene, scales="free_y", nrow=1) +
  stat_pvalue_manual(
    stat.test,  label = "p.signif", tip.length = 0, hide.ns = F
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.4))) +
  scale_color_manual(values = gntp_col) +
  theme_cowplot(15) +
  theme(strip.background=element_rect(colour="white",
                                    fill="white"), legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        strip.text.x = element_text(face = "bold.italic"),
        plot.title = element_text(size=13)) +
  labs(x = NULL, y = NULL) +
  ggtitle("Thymus")
```

### Spleen

```{r}
qpcr_data_SPL <- qpcr_data %>% filter(Tissue == "Spleen")

stat.test <- qpcr_data_SPL %>%
  group_by(Gene) %>%
  t_test(FC ~ Genotype) %>%
  adjust_pvalue() %>%
  add_significance("p") %>%
  add_xy_position(x = "Genotype", dodge = 0.8, scales="free_y") %>%
  filter(p.signif != "ns")

qpcr_data_SPL_summarized <- qpcr_data_SPL %>%
  group_by(Gene, Genotype) %>%
  mutate(n = n()) %>%
  summarise(Mean = mean(FC), SEM = sd(FC)/sqrt(n)) %>%
  distinct()

p_SPL <- ggplot(qpcr_data_SPL_summarized, aes(Genotype, Mean, color = Genotype)) + 
  geom_errorbar(aes(x=Genotype, ymin=Mean-SEM, ymax=Mean+SEM), width=0.4, position = position_dodge(.8)) +
  geom_errorbar(aes(x=Genotype, ymin=Mean, ymax=Mean), width=0.6, position = position_dodge(.8)) +
  geom_dotplot(data = qpcr_data_SPL, aes(x=Genotype, y=FC, color = Genotype), binaxis = "y", stackdir = "center", position = position_dodge(.8)) +
  facet_wrap(~Gene, scales="free_y", nrow=1) +
  stat_pvalue_manual(
    stat.test,  label = "p.signif", tip.length = 0, hide.ns = T
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.4))) +
  scale_color_manual(values = gntp_col) +
  theme_cowplot(15) +
  theme(strip.background=element_rect(colour="white",
                                    fill="white"), legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        strip.text.x = element_text(face = "bold.italic"),
        plot.title = element_text(size=13)) +
  labs(x = NULL, y = NULL) +
  ggtitle("Spleen")
```

### LN

```{r}
qpcr_data_LN <- qpcr_data %>% filter(Tissue == "LN")

stat.test <- qpcr_data_LN %>%
  group_by(Gene) %>%
  t_test(FC ~ Genotype) %>%
  adjust_pvalue() %>%
  add_significance("p") %>%
  add_xy_position(x = "Genotype", dodge = 0.8, scales="free_y") %>%
  filter(p.signif != "ns")

qpcr_data_LN_summarized <- qpcr_data_LN %>%
  group_by(Gene, Genotype) %>%
  mutate(n = n()) %>%
  summarise(Mean = mean(FC), SEM = sd(FC)/sqrt(n)) %>%
  distinct()

p_LN <- ggplot(qpcr_data_LN_summarized, aes(Genotype, Mean, color = Genotype)) + 
  geom_errorbar(aes(x=Genotype, ymin=Mean-SEM, ymax=Mean+SEM), width=0.4, position = position_dodge(.8)) +
  geom_errorbar(aes(x=Genotype, ymin=Mean, ymax=Mean), width=0.6, position = position_dodge(.8)) +
  geom_dotplot(data = qpcr_data_LN, aes(x=Genotype, y=FC, color = Genotype), binaxis = "y", stackdir = "center", position = position_dodge(.8)) +
  facet_wrap(~Gene, scales="free_y", nrow=1) +
  stat_pvalue_manual(
    stat.test,  label = "p.signif", tip.length = 0, hide.ns = T
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.4))) +
  scale_color_manual(values = gntp_col) +
  theme_cowplot(15) +
  theme(strip.background=element_rect(colour="white",
                                    fill="white"), legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        strip.text.x = element_text(face = "bold.italic"),
        plot.title = element_text(size=13)) +
  labs(x = NULL, y = NULL) +
  ggtitle("Lymph node")
```

```{r, fig.width=15, fig.height=7}
P_I <- p_THY / p_SPL / p_LN

P_I
```

```{r}
sessionInfo()
```

