---
title: "JEM Figure 3"
author: "Maksym Zarodniuk"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: html_document
---

```{r setup, warning=F, message=F}
library(Seurat)
library(RColorBrewer)
library(tidyverse)
library(cowplot)
library(ggdendro)
library(ggtree)
library(patchwork)
library(viridis)
library(aplot)
library(ggtext)
library(ggpubr)
library(lemon)
library(biomaRt)
library(ggrepel)
library(scran)
library(scuttle)
library(edgeR)
library(ComplexHeatmap)
library(cba)
library(dendextend)
library(pvclust)
library(slingshot)
library(tradeSeq)
library(scales)
library(ggridges)
library(MetBrewer)
```

```{r}
remote_dir <- "/Volumes/TOSHIBA/molpat/APECED_rats/analysis/single_cell/sc_rat_thymus/data/rds_objects/"
seurat_obj <- readRDS(paste0(remote_dir, "TECs_integrated_seurat_object.rds"))
```

## 3A

```{r}
col_vec <- colorRampPalette(brewer.pal(9, "Set1"))(18)[1:13]
color_mapping <- col_vec
names(color_mapping) <- levels(seurat_obj$cell.type)

P_A <- DimPlot(seurat_obj,
        label = TRUE,
        label.size = 5,
        group.by = "cell.type.idx",
        cols = col_vec) +
  theme(legend.position = "none") +
  labs(title = NULL)

P_A_legend <- DimPlot(seurat_obj,
                group.by = "legend",
                cols = col_vec,
                label = TRUE)

P_A_legend <- plot_grid(get_legend(P_A_legend))

P_A + P_A_legend
```

## 3B

```{r, fig.height=15, fig.width=7}
source("util.R")

markers_df <- read_tsv("data/Figure_3/dotplot_gene_specificity.tsv")
markers_df$Color <- color_mapping[match(markers_df$gene.corresp, names(color_mapping))]
markers_df <- markers_df %>%
  replace_na(list(Color = "#b1b1b1")) %>%
  mutate(y.label = paste("<span style = 'color:",
                         Color,
                         ";'>",
                         gene,
                         "</span>", sep = ""))

dfB <- dot_plot(object = seurat_obj[,seurat_obj$genotype=="HE"],
        assay = "RNA",
        features = markers_df$gene,
        cluster.idents = TRUE,
        group.by = "cell.type") %>%
  dplyr::rename(`% Expressing` = pct.exp, `Cell type` = id) %>%
  left_join(markers_df, by = c("features.plot" = "gene"))

dfB$features.plot <- factor(dfB$features.plot, levels = unique(markers_df$gene))

dfB <- dfB %>%
  filter(`% Expressing` > 1)
  
dfB$y.label <- factor(dfB$y.label, levels = markers_df$y.label)
dfB$`Cell type` <- factor(dfB$`Cell type`, levels = (levels(seurat_obj$cell.type)))

dotplot <- dfB %>%
  ggplot(aes(y=y.label, x = `Cell type`, color = avg.exp.scaled, size = `% Expressing`)) + 
  geom_point() +
  geom_point(aes(size=`% Expressing`), shape = 21, colour="black", stroke=0.5) +
  theme_cowplot(13) +
  scale_radius(limits = c(0, 100)) +
  scale_size(range = c(0, 3.2)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.text.y = element_markdown(),
        axis.line = element_blank()) +
  ylab(NULL) +
  xlab(NULL) +
  theme(axis.ticks = element_blank()) +
  scale_x_discrete(position = "top") +
  viridis::scale_colour_viridis(option="magma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white")))

labels <- ggplot(dfB %>%
                   distinct(`Cell type`),
                 aes(y = factor(1), x = `Cell type`, fill = `Cell type`)) + 
  geom_tile() +
  scale_fill_manual(values = color_mapping) + 
  theme_nothing() +
  xlim2(dotplot) +
  xlab(NULL)

P_B <- labels +
  dotplot + 
  plot_layout(nrow = 2, heights = c(.2, 9))

P_B
```

## 3C

```{r}
aire_dep_genes <- readLines("data/Figure_3/Rat_AireReg_genes.txt")
trg_genes <- read_tsv("data/Figure_3/Rat_TRG.tsv") %>%
  drop_na()

seurat_obj_sub <- seurat_obj[, seurat_obj$genotype == "HE"]
rat_genes <- rownames(seurat_obj_sub)

DefaultAssay(seurat_obj_sub) <- "RNA"

aire_dep_genes <- aire_dep_genes[aire_dep_genes %in% rat_genes]
seurat_obj_sub <- AddModuleScore(seurat_obj_sub,
               features = list(aire_dep_genes),
               name = "AireDep",
               genes.pool = NULL,
               n.bin = 5,
               ctrl.size = length(x),
               use.k = FALSE,
               seed = 1)
colnames(seurat_obj_sub@meta.data)[ncol(seurat_obj_sub@meta.data)] <- "AireDep"

aire_dep_genes <- trg_genes$SYMBOL.Rn
aire_dep_genes <- aire_dep_genes[!is.na(aire_dep_genes)]
aire_dep_genes <- aire_dep_genes[aire_dep_genes %in% rat_genes]
seurat_obj_sub <- AddModuleScore(seurat_obj_sub,
               features = list(aire_dep_genes),
               name = "TRG",
               genes.pool = NULL,
               n.bin = 10,
               #ctrl.size = length(x),
               use.k = FALSE,
               seed = 1)

colnames(seurat_obj_sub@meta.data)[ncol(seurat_obj_sub@meta.data)] <- "TRG"

dfC <- seurat_obj_sub@meta.data

P_C1 <- ggviolin(dfC,
         x = "cell.type",
         y = "TRG",
         fill = "cell.type",
         palette = color_mapping,
 add = "boxplot") +
  labs(x = NULL, y = "Signature score") +
  coord_capped_cart(left = "both") +
  theme_cowplot(16) +
  theme(legend.position = "none", axis.text.x = element_blank()) +
  ggtitle("TRA")

P_C2 <- ggviolin(dfC,
         x = "cell.type",
         y = "AireDep",
         fill = "cell.type",
         palette = color_mapping,
 add = "boxplot") +
  labs(x = NULL, y = "Signature score") +
  coord_capped_cart(left = "both") +
  theme_cowplot(16) +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Aire-dep. genes")

P_C <- P_C1 + P_C2 + plot_layout(ncol = 1)

P_C
```

## 3D

```{r}
mart <- useMart("ensembl", dataset = "rnorvegicus_gene_ensembl")
gene_annotations <- getBM(attributes = c("rgd_symbol", "gene_biotype"), mart = mart)

pt_coding_genes <- intersect(gene_annotations[gene_annotations$gene_biotype=="protein_coding",]$rgd_symbol, rownames(seurat_obj))
```

```{r, eval=F}
library(iNEXT)
library(ggrepel)

cell_types_of_interest <- c("mTEC II.1 (prolif.)", "mTEC II.1", "mTEC II.2", "mTEC II.3", "mTEC III")
l = list()
for (i in cell_types_of_interest) {
  x <- subset(seurat_obj[,seurat_obj$genotype=="HE"], idents = i)
  mat = x@assays$RNA@counts[pt_coding_genes,]
  l[[i]] <- rowSums(mat)
}

# takes a while to run
res <- iNEXT(l[[1]],
             q = 0,
             endpoint = 10,
             datatype = "abundance",
             nboot = 1)
```

```{r}
res <- readRDS("data/Figure_3/l_inext_output.rds")

rarefaction_df <- res[[2]]$size_based
rarefaction_df$Method[rarefaction_df$Method=="Observed"] <- "Rarefaction"
rarefaction_df$lty <- factor(rarefaction_df$Method, levels=c("Rarefaction", "Extrapolation"))

P_D <- rarefaction_df %>%
  filter(Assemblage != "mTEC I") %>%
    group_by(Assemblage, Order.q) %>%
    mutate(label = if_else(m == max(m), as.character(Assemblage), NA_character_)) %>%
    ggplot(aes(x = m, y = qD, color = Assemblage, label = Assemblage)) +
    geom_line(aes_string(linetype="lty"), lwd=1, alpha = 0.8) +
    geom_ribbon(aes(ymin=qD.LCL, ymax=qD.UCL, fill=Assemblage, color = NULL), alpha=0.5) +
    geom_label_repel(aes(label = label),
                     nudge_x = 2,
                     na.rm = TRUE,
                     size = 5,
                     box.padding = .6,
                     show.legend = FALSE,
                     force = 1000,
                     force_pull=0,
                     alpha = 0.8) +
    scale_colour_manual(values = color_mapping[names(color_mapping) %in% rarefaction_df$Assemblage]) +
    scale_fill_manual(values = color_mapping[names(color_mapping) %in% rarefaction_df$Assemblage]) +
    theme_cowplot(18) +
    labs(x = "Pooled UMI counts", y = "Expressed genes") +
    theme(legend.position = "right")

P_D
```

```{r, eval=F}
res <- iNEXT(l,
             q = 0,
             datatype = "abundance", size = 2000000)
```

```{r}
res <- readRDS("data/Figure_3/l_inext_output_2M_endpoint.rds")

res <- res[[2]]$size_based %>%
  filter(m==2000000) %>%
  mutate(CL = qD-qD.LCL) %>%
  filter(Assemblage != "mTEC I")
  
res$Assemblage <- factor(res$Assemblage, levels = c("mTEC II.1", "mTEC II.1 (prolif.)", "mTEC II.2", "mTEC II.3", "mTEC III"))

ref <- res %>% filter(Assemblage == "mTEC II.2")
ref_mean <- ref$qD
ref_SE <- (ref$qD.UCL - ref$qD.LCL) / (2 * qnorm(0.975))  # Approximate SE

# p value approximation
p_values <- res %>%
  filter(Assemblage != "mTEC II.2") %>%
  rowwise() %>%
  mutate(
    mean_diff = ref_mean - qD,
    SE_other = (qD.UCL - qD.LCL) / (2 * qnorm(0.975)),
    pooled_SE = sqrt(ref_SE^2 + SE_other^2),
    Z = mean_diff / pooled_SE,
    p_value = 2 * (1 - pnorm(abs(Z)))  # Two-tailed test
  ) %>%
  dplyr::select(Assemblage, p_value)

P_D <- ggplot(res, aes(Assemblage, qD, color = Assemblage)) + 
  geom_errorbar(aes(x=Assemblage, ymin=qD-CL, ymax=qD+CL), width=0.4, position = position_dodge(.8)) +
  geom_errorbar(aes(x=Assemblage, ymin=qD, ymax=qD), width=0.6, position = position_dodge(.8)) +
  scale_colour_manual(values = color_mapping[names(color_mapping) %in% res$Assemblage]) +
  theme_cowplot(16) +
  labs(x = NULL, y = "qD") +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

P_D
```
## 3E

```{r}
source("util.R")

exprs_mat <- generate_pseudobulk_samples(seurat_obj[,seurat_obj$genotype=="HE"], filter = F)
cor_mat <- cor(exprs_mat)
dist <- as.dist(1-cor_mat)
clust <- hclust(dist, method = "average")
order <- order.optimal(dist, clust$merge)
dd <- as.dendrogram(clust)
labels_colors(dd) <- color_mapping[match(clust$labels[clust$order], names(color_mapping))]
```
```{r, eval=F}
result <- pvclust(exprs_mat, method.dist="cor", method.hclust="average", nboot=2000, parallel=TRUE)
plot(result)
```

```{r}
par(mar=c(10,3,1,1))
plot(rotate(dd, rev(names(order$order))), ylab = "Correlation distance")
text(5.5, 0.03, "*", col = "red", cex = 1.5)
text(7.5, 0.03, "*", col = "red", cex = 1.5)
text(6.5, 0.045, "*", col = "red", cex = 1.5)
text(5.3, 0.065, "*", col = "red", cex = 1.5)
text(7.15, 0.0775, "*", col = "red", cex = 1.5)
text(5.1, 0.115, "*", col = "red", cex = 1.5)
text(3.55, 0.1425, "*", col = "red", cex = 1.5)
text(3.55, 0.1425, "*", col = "red", cex = 1.5)
text(7.55, 0.17, "*", col = "red", cex = 1.5)
text(11.5, 0.135, "*", col = "red", cex = 1.5)
```

## 3F

```{r, fig.height=6, fig.width=5}
Idents(seurat_obj) <- "integrated_snn_res.1"
mtecs <- subset(x = seurat_obj, idents = c(11, 14, 15, 16, 17, 19))
DefaultAssay(mtecs) <- "integrated"
Idents(mtecs) <- "cell.type"

# Color palette
col_vec <- colorRampPalette(brewer.pal(9, "Set1"))(18)[1:13]
color_mapping <- col_vec
names(color_mapping) <- levels(seurat_obj$cell.type)

sce <- as.SingleCellExperiment(mtecs, assay = "RNA")
sce <- slingshot(sce, reducedDim = 'UMAP', clusterLabels = colData(sce)[["cell.type"]],
                 start.clus = "mTEC II.1 (prolif.)",
                 end.clus = "mTEC III")

lin1 <- getLineages(sce, colData(sce)[["cell.type"]], start.clus = "mTEC II.1 (prolif.)", end.clus = "mTEC III", reducedDim = "UMAP")
colData(sce)[["cell.type"]] <- factor(colData(sce)[["cell.type"]], levels = c("mTEC II.1 (prolif.)", "mTEC II.1", "mTEC II.2", "mTEC II.3", "mTEC III"))

par(
    mar = c(3, 3, 1, 1),
    mgp = c(2, 1, 0)
)
plot(reducedDims(sce)$UMAP, col = color_mapping[match(colData(sce)[["cell.type"]], names(color_mapping))], asp = .6, pch = 16, cex = .4, ylim = c(-12, -3))
lines(SlingshotDataSet(sce))
```
```{r}
par(
    mar = c(3, 3, 1, 1),
    mgp = c(2, 1, 0)
)
col_vec <- viridis::magma(100)[cut(sce$slingPseudotime_1, breaks = 100)]
col_vec[is.na(col_vec)] <- "#D3D3D350"
plot(reducedDims(sce)$UMAP, asp = 0.6, pch = 16, xlab = "UMAP-1", ylab = "UMAP-2", cex = 0.4,
 col = col_vec)
lines(SlingshotDataSet(sce))
```

## 3H

```{r}
pseudotime_distribution <- slingPseudotime(sce) %>%
  as.data.frame() %>%
  rownames_to_column("Cell") %>%
  left_join(mtecs@meta.data %>% dplyr::select(cell.type, genotype) %>% rownames_to_column("Cell"))

pseudotime_distribution$cell.type <- factor(pseudotime_distribution$cell.type, levels = c("mTEC II.1 (prolif.)", "mTEC II.1", "mTEC II.2", "mTEC II.3", "mTEC III"))

P_H1 <- ggplot(pseudotime_distribution, aes(x=Lineage1, fill=genotype)) +
  geom_density(alpha=0.4) +
  xlim(-3, 15) +
  theme_minimal(base_size = 14) +
  labs(x = "Pseudotime", y = "Density", fill = "Genotype") +
  theme(panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank()) +
  scale_fill_manual(values = rev(met.brewer("Nizami", 2)))

# ks.test(slingPseudotime(sce)[colData(sce)$genotype == "HE", 1],
#        slingPseudotime(sce)[colData(sce)$genotype == "KO", 1])

pseudotime_distribution$cell.type <- factor(pseudotime_distribution$cell.type, levels = rev(levels(pseudotime_distribution$cell.type)))

P_H2 <- ggplot(pseudotime_distribution, aes(x = Lineage1, y = cell.type, fill = cell.type)) +
  geom_density_ridges(show.legend = TRUE) +
  theme_ridges() +
  theme(legend.position = "none") +
  labs(x = "Pseudotime", y = NULL, fill = "Cell type") +
  xlim(-3, 28) +
  theme_minimal(base_size = 16) +
  xlim(-3, 15) +
  theme(panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank()) +
  scale_fill_manual(values = color_mapping[names(color_mapping) %in% unique(pseudotime_distribution$cell.type)])

P_H2
```

## 3I

```{r, eval=F}
set.seed(3)
icMat <- evaluateK(counts = as.matrix(assays(sce)$counts),
                   pseudotime = slingPseudotime(sce),
                   cellWeights = slingCurveWeights(sce),
                   conditions = factor(colData(sce)$genotype),
                   nGenes = 300,
                   k = 3:7)
```

```{r, eval=F}
# GAM fitting takes a while
sce <- fitGAM(sce, conditions = factor(colData(sce)$genotype),
              nknots = 6, parallel=T)

gene_vec <- c("Aire", "Fezf2", "Ins2","Gip", "Nts")
plot_vec <- paste("p", 1:length(gene_vec), sep = "")

for (i in 1:length(gene_vec)) {
  gene_name <- gene_vec[i]
  if (sum(grepl(gene_name, rowData(sce)$tradeSeq$name)) != 0) {
      p <- plot_smoothers_fun(sce, gene_name) + theme_cowplot(16) + theme(legend.position = "none") + ylim(0, 4.5)
      assign(plot_vec[i], p)
  }
}

p2 <- p2 + labs(y = NULL)
p3 <- p3 + labs(y = NULL)
p4 <- p4 + labs(y = NULL)
p5 <- p5 + labs(y = NULL)

P_I <- plot_grid(p1, p2, p3, p4, p5, nrow = 1)

P_I
```

## S3A

```{r}
gntp_col <- met.brewer("Nizami", 2)[c(2, 1)]
names(gntp_col) <- c("HE", "KO")

P_S3A <- seurat_obj@meta.data %>%
  group_by(genotype, seq_folder, cell.type) %>%
  summarise(Count = n()) %>%
  mutate(Freq = Count/sum(Count)) %>%
  ggplot(aes(cell.type, Freq, fill = genotype)) +
  stat_summary(geom = "bar", fun = mean, position = "dodge") +
  stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge") +
  geom_point(position = position_dodge(0.8), alpha=0.3, size = 0.5) +
  scale_fill_manual(values = gntp_col) +
  theme_cowplot() +
  theme(axis.text.x = element_text(angle = 90,  vjust = 0.5, hjust=1)) +
  labs(x = NULL, y = "Frequency")

P_S3A
```

```{r}
sessionInfo()
```